### ISSUE TITLE
Duplicate Key Error

### ISSUE THREAD

**Issue by super3** [Storj/metadisk-client#26] opened 2016-05-25 18:30 UTC
### Package Versions

Replace the values below using the output from `npm list -g storj`.

```
└─┬ storj-bridge-client@0.4.3
  └── storj@0.6.16
```

Replace the values below using the output from `node --version`.

```
v4.2.3
```
### Expected Behavior

Upload works.
### Actual Behavior

Fails on duplicate key error.

```
root@storj:~/samples# sh flood.sh
10240+0 records in
10240+0 records out
10485760 bytes (10 MB) copied, 1.49259 s, 7.0 MB/s
 [info]   Generating encryption key...
 [info]   Encrypting file "upfile"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
 [error]  E11000 duplicate key error collection: bridge.usernonces index: user_1_nonce_1 dup key: { : "shawn@storj.io            ", : "2201833f-fbce-4645-af79-f8a65e1f3014" }
```
### Steps to Reproduce

Not sure.

**Comment by super3** [comment] 2016-05-25 18:31
@phutchins Saw this yesterday and may or may not be tied to the nonce issue. Just documenting it for now.

**Comment by niahmiah** [comment] 2016-05-25 18:38
dupe of https://github.com/Storj/bridge-client-javascript/issues/25

**Closed as completed** 2016-05-25 19:15 UTC
