### ISSUE TITLE
Upload filesize limited to 8MB ?

### ISSUE THREAD

**Issue by Th3Van** [Storj/metadisk-client#25] opened 2016-05-25 17:46 UTC
I'm unable to upload files bigger than 8MB, using storjcli with the "uploadfile" option.
Anything larger than that is returning with a [ERROR] and times out.

I've been running some tests using storj.dk and api.storj.io bridge servers, but with same result.
Every "accepting storage contract / CONSIGN" are going out just fine, but the last one is always missing, if file size are greater than 8MB.

**8MB file -> Storj.dk bridge :** 

<pre><code>Storj.dk - storjcli client - 8MB file : 
 root@Server014:~/storjcli/script# storjcli -k VaNkEy16 uploadfile 574224fc5a3ce4e2697c30a2 ./Storj.dk-8MB-File.tmp
 [info]   Generating encryption key...
 [info]   Encrypting file "./Storj.dk-8MB-File.tmp"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
 [info]   Encryption key saved to keyring.
 [info]   File successfully stored in bucket.
 [info]   Name: Storj.dk-8MB-File.tmp, Type: application/octet-stream, Size: 8388624 bytes, ID: 57459d65785767c21b431d01

Storj.dk - Storj-brige server - 8MB file :
 {"level":"info","message":"creating PUSH token for 574224fc5a3ce4e2697c30a2","timestamp":"2016-05-25T12:37:05.635Z"}
 {"level":"info","message":"publishing message on topic \"0f01020202\"","timestamp":"2016-05-25T12:37:05.776Z"}
 {"level":"info","message":"publishing message on topic \"0f01020202\"","timestamp":"2016-05-25T12:37:06.042Z"}
 {"level":"info","message":"accepting storage contract offer from d7a1147c7398413bed31ab9a3145ac842e1b50b2","timestamp":"2016-05-25T12:37:08.627Z"}
 {"level":"info","message":"sending CONSIGN message to {\"protocol\":\"0.6.15\",\"address\":\"a.storj.eu\",\"port\":8290,\"nodeID\":\"d7a1147c7398413bed31ab9a3145ac842e1b50b2\",\"lastSeen\":1464179828655}","timestamp":"2016-05-25T12:37:08.655Z"}
 {"level":"info","message":"accepting storage contract offer from d7a1147c7398413bed31ab9a3145ac842e1b50b2","timestamp":"2016-05-25T12:37:08.977Z"} 
 {"level":"info","message":"sending CONSIGN message to {\"protocol\":\"0.6.15\",\"address\":\"a.storj.eu\",\"port\":8290,\"nodeID\":\"d7a1147c7398413bed31ab9a3145ac842e1b50b2\",\"lastSeen\":1464179828994}","timestamp":"2016-05-25T12:37:08.994Z"}

(2 x publishing message - 2 x CONSIGN message) </code></pre>

**9MB file -> Storj.dk bridge :** 

<pre><code>Storj.dk - storjcli client - 9MB file : 
 root@Server014:~/storjcli/script# storjcli -k VaNkEy16 uploadfile 574224fc5a3ce4e2697c30a2 ./Storj.dk-9MB-File.tmp
 [info]   Generating encryption key...
 [info]   Encrypting file "./Storj.dk-9MB-File.tmp"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
[error]  socket hang up 

Storj.dk - Storj-brige server - 9MB file :
 {"level":"info","message":"creating PUSH token for 574224fc5a3ce4e2697c30a2","timestamp":"2016-05-25T12:41:32.181Z"}
 {"level":"info","message":"publishing message on topic \"0f01020202\"","timestamp":"2016-05-25T12:41:32.304Z"}
 {"level":"info","message":"publishing message on topic \"0f01020202\"","timestamp":"2016-05-25T12:41:32.336Z"}
 {"level":"info","message":"publishing message on topic \"0f01020202\"","timestamp":"2016-05-25T12:41:32.572Z"}
 {"level":"info","message":"accepting storage contract offer from d7a1147c7398413bed31ab9a3145ac842e1b50b2","timestamp":"2016-05-25T12:41:35.630Z"}
 {"level":"info","message":"sending CONSIGN message to {\"protocol\":\"0.6.15\",\"address\":\"a.storj.eu\",\"port\":8290,\"nodeID\":\"d7a1147c7398413bed31ab9a3145ac842e1b50b2\",\"lastSeen\":1464180095648}","timestamp":"2016-05-25T12:41:35.648Z"}
 {"level":"info","message":"accepting storage contract offer from d7a1147c7398413bed31ab9a3145ac842e1b50b2","timestamp":"2016-05-25T12:41:35.778Z"}
 {"level":"info","message":"sending CONSIGN message to {\"protocol\":\"0.6.15\",\"address\":\"a.storj.eu\",\"port\":8290,\"nodeID\":\"d7a1147c7398413bed31ab9a3145ac842e1b50b2\",\"lastSeen\":1464180095840}","timestamp":"2016-05-25T12:41:35.840Z"}

(3 x publishing message - but only 2 x CONSIGN message)
</code></pre>

**32MB file -> Storj.dk bridge :**

<pre><code>
Storj.dk - storjcli client - 32MB file : 
 root@Server014:~/storjcli/script# storjcli -k VaNkEy16 uploadfile 574224fc5a3ce4e2697c30a2 ./Storj.dk-32MB-File.tmp
 [info]   Generating encryption key...
 [info]   Encrypting file "./Storj.dk-32MB-File.tmp"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
 [error]  socket hang up

Storj.dk - Storj-brige server - 32MB file :
 {"level":"info","message":"publishing message on topic \"0f01020202\"","timestamp":"2016-05-25T12:48:41.872Z"}
 {"level":"info","message":"publishing message on topic \"0f01020202\"","timestamp":"2016-05-25T12:48:42.024Z"}
 {"level":"info","message":"publishing message on topic \"0f01020202\"","timestamp":"2016-05-25T12:48:42.047Z"}
 {"level":"info","message":"publishing message on topic \"0f01020202\"","timestamp":"2016-05-25T12:48:42.097Z"}
 {"level":"info","message":"accepting storage contract offer from d7a1147c7398413bed31ab9a3145ac842e1b50b2","timestamp":"2016-05-25T12:48:47.566Z"}
 {"level":"info","message":"accepting storage contract offer from d7a1147c7398413bed31ab9a3145ac842e1b50b2","timestamp":"2016-05-25T12:48:47.584Z"}
 {"level":"info","message":"accepting storage contract offer from d7a1147c7398413bed31ab9a3145ac842e1b50b2","timestamp":"2016-05-25T12:48:47.596Z"}
 {"level":"info","message":"sending CONSIGN message to {\"protocol\":\"0.6.15\",\"address\":\"a.storj.eu\",\"port\":8290,\"nodeID\":\"d7a1147c7398413bed31ab9a3145ac842e1b50b2\",\"lastSeen\":1464180527623}","timestamp":"2016-05-25T12:48:47.623Z"}
 {"level":"info","message":"sending CONSIGN message to {\"protocol\":\"0.6.15\",\"address\":\"a.storj.eu\",\"port\":8290,\"nodeID\":\"d7a1147c7398413bed31ab9a3145ac842e1b50b2\",\"lastSeen\":1464180527643}","timestamp":"2016-05-25T12:48:47.643Z"}
 {"level":"info","message":"sending CONSIGN message to {\"protocol\":\"0.6.15\",\"address\":\"a.storj.eu\",\"port\":8290,\"nodeID\":\"d7a1147c7398413bed31ab9a3145ac842e1b50b2\",\"lastSeen\":1464180527664}","timestamp":"2016-05-25T12:48:47.664Z"}

(4 x publishing message - but only 3 x CONSIGN message)
</code></pre>

**8/9/32MB file -> api.storj.io bridge :**

<pre><code>
api.storj.io - storjcli client - 8MB file : 
 root@Server022:~/bridge-client-javascript/script# storjcli -k VaNkEy16 uploadfile 57449f473142a39c6f541eda ./Storj.dk-8MB-File.tmp
 [info]   Generating encryption key...
 [info]   Encrypting file "./Storj.dk-8MB-File.tmp"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
 [info]   Encryption key saved to keyring.
 [info]   File successfully stored in bucket.
 [info]   Name: Storj.dk-8MB-File.tmp, Type: application/octet-stream, Size: 8388624 bytes, ID: 574585603142a39c6f5433a9

api.storj.io - storjcli client - 9MB file : 
 root@Server022:~/bridge-client-javascript/script# storjcli -k VaNkEy16 uploadfile 57449f473142a39c6f541eda ./Storj.dk-9MB-File.tmp
 [info]   Generating encryption key...
 [info]   Encrypting file "./Storj.dk-9MB-File.tmp"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
 [error]  E11000 duplicate key error collection: bridge.usernonces index: user_1_nonce_1 dup key: { : "****removed******", : "09c3373b-25b7-4180-85aa-e177551d1f70" }

api.storj.io - storjcli client - 32MB file : 
 root@Server022:~/bridge-client-javascript/script# storjcli -k VaNkEy16 uploadfile 57449f473142a39c6f541eda ./Storj.dk-10MB-File.tmp
 [info]   Generating encryption key...
 [info]   Encrypting file "./Storj.dk-10MB-File.tmp"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
 [error]  E11000 duplicate key error collection: bridge.usernonces index: user_1_nonce_1 dup key: { : "****removed******", : "02911fab-ebc3-4d97-b65a-3097c5abf31a" }
</code></pre>

[Storjcli-bridge upload file test - server014.storj.dk.txt](https://github.com/Storj/bridge-client-javascript/files/282534/Storjcli-bridge.upload.file.test.-.server014.storj.dk.txt)
[Storjcli-bridge upload file test - api.storj.io.txt](https://github.com/Storj/bridge-client-javascript/files/282533/Storjcli-bridge.upload.file.test.-.api.storj.io.txt)

[Storj.dk-bridge-log-files-Th3Van.zip](https://github.com/Storj/bridge-client-javascript/files/282547/Storj.dk-bridge-log-files-Th3Van.zip)

Regards,
Th3Van
storj.dk

**Comment by 161chihuahuas** [comment] 2016-05-25 18:12
@niahmiah do you have any time to look at this?

**Comment by niahmiah** [comment] 2016-05-25 21:34
This seems to indicate an issue with the nginx config. Specifically, the errors about the duplicate nonce indicate that something is reattempting a request, outside of the client. @phutchins is investigating.

**Comment by 161chihuahuas** [comment] 2016-05-26 21:57
@niahmiah @phutchins any movement on this? I think I have confidently ruled out it being an issue with the client/protocol.

**Comment by phutchins** [comment] 2016-05-26 23:36
I've made the changes to the nginx config to stop the duplicate key error. This exposes the underlying issue where the API is not responding to the request. @niahmiah has added extra debug logging to the bridge code and we attempted to duplicate the issue in staging with no luck. It seems load is needed to duplicate. Our next step is to run the code with the debug logging in production and duplicate the error to troubleshoot.

**Comment by 161chihuahuas** [comment] 2016-05-27 02:38
@phutchins @niahmiah if load is the issue, then that happened sooner than I thought. Since the API and the network interface run in the same process, the network chatter hogs the event loop, which likely causes these requests to the API to get back seated, which causes the enormous latency and the resulting nginx timeouts. 

I think that we need to pull the `RenterInterface` usage in bridge out into a micro service so we can run a little swarm of those bad boys and bridge can select one during an API request. This would also alleviate some of the issues with using the API host as a network seed for farmers. 

I wanted to write a [dnode](https://github.com/substack/dnode) plugin for core's network module anyway, so this would be a good reason to do so. How does that sound to you guys, assuming that this is in fact the issue?

**Comment by phutchins** [comment] 2016-05-28 14:41
@gordonwritescode I'm running some tests now but it does sound like the issue lies in the time it takes when getting contracts for shards while the network is busy.

I'm interested to see the outcome of my tests if I can replicate the issue but I think we should go ahead with your solution of splitting out the network bits from the bridge...

**Comment by 161chihuahuas** [comment] 2016-05-28 14:57
@phutchins
- https://github.com/Storj/core/issues/139
- https://github.com/Storj/core/issues/140

**Comment by 161chihuahuas** [comment] 2016-05-28 15:00
- https://github.com/Storj/bridge/issues/80

**Comment by phutchins** [comment] 2016-05-28 15:13
Awesome. 👍

**Comment by 161chihuahuas** [comment] 2016-05-31 00:09
Closing this as it is not a bug in the client and there are now separate issues tracking the real issue.

**Closed as completed** 2016-05-31 00:09 UTC
Labels: bug
